<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.1 (Python 3.8.8 on win32)" generated="20210621 00:59:11.450" rpa="false" schemaversion="2">
<suite id="s1" name="automacaoSite" source="d:\projetosParticular\Prime\PrimeExperts\tests\automacaoSite.robot">
<test id="s1-t1" name="Caso de Teste 04: Adicionar Cliente">
<kw name="Abrir o navegador" library="kws_automation" type="SETUP">
<kw name="Open Browser">
<arg>browser=${BROWSER}</arg>
<msg timestamp="20210621 00:59:11.911" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20210621 00:59:11.911" endtime="20210621 00:59:11.911"/>
</kw>
<kw name="Maximize Browser Window">
<status status="NOT RUN" starttime="20210621 00:59:11.914" endtime="20210621 00:59:11.914"/>
</kw>
<status status="FAIL" starttime="20210621 00:59:11.906" endtime="20210621 00:59:11.914"/>
</kw>
<kw name="Fechar o navegador" library="kws_automation" type="TEARDOWN">
<kw name="Close Browser">
<msg timestamp="20210621 00:59:11.917" level="FAIL">No keyword with name 'Close Browser' found.</msg>
<status status="FAIL" starttime="20210621 00:59:11.917" endtime="20210621 00:59:11.917"/>
</kw>
<status status="FAIL" starttime="20210621 00:59:11.914" endtime="20210621 00:59:11.918">No keyword with name 'Close Browser' found.</status>
</kw>
<status status="FAIL" starttime="20210621 00:59:11.904" endtime="20210621 00:59:11.918">Setup failed:
No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.</status>
</test>
<doc>Neste arquivo estarão presentes nossos primeiros fluxos
de automação web e seus respectivos cenários automatizados.</doc>
<status status="FAIL" starttime="20210621 00:59:11.453" endtime="20210621 00:59:11.919"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="automacaoSite">automacaoSite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210621 00:59:11.701" level="ERROR">Error in file 'd:\projetosParticular\Prime\PrimeExperts\resources\kw\kws_automation.robot' on line 4: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\Users\AS\.vscode\extensions\robocorp.robotframework-lsp-0.18.0\src\robotframework_debug_adapter
  d:\projetosParticular\Prime\PrimeExperts
  c:\Users\AS\.vscode\extensions\robocorp.robotframework-lsp-0.18.0\src
  c:\Users\AS\.vscode\extensions\robocorp.robotframework-lsp-0.18.0\src\robotframework_ls\vendored
  C:\Users\AS\AppData\Local\robocorp\live\2aa1db4bb1a50e5e\python38.zip
  C:\Users\AS\AppData\Local\robocorp\live\2aa1db4bb1a50e5e\DLLs
  C:\Users\AS\AppData\Local\robocorp\live\2aa1db4bb1a50e5e\lib
  C:\Users\AS\AppData\Local\robocorp\live\2aa1db4bb1a50e5e
  C:\Users\AS\AppData\Roaming\Python\Python38\site-packages
  C:\Users\AS\AppData\Roaming\Python\Python38\site-packages\win32
  C:\Users\AS\AppData\Roaming\Python\Python38\site-packages\win32\lib
  C:\Users\AS\AppData\Roaming\Python\Python38\site-packages\Pythonwin
  C:\Users\AS\AppData\Local\robocorp\live\2aa1db4bb1a50e5e\lib\site-packages</msg>
<msg timestamp="20210621 00:59:11.902" level="ERROR">Error in file 'd:\projetosParticular\Prime\PrimeExperts\resources\kw\kws_automation.robot' on line 8: Error in file 'd:\projetosParticular\Prime\PrimeExperts\tests\exercicios.robot' on line 8: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
